spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/tony_ecommerce
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080

jwt:
  secret: your-secret-key-should-be-very-long-and-secure-123456789
  expiration: 86400000 # 24 hours 