name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: 設定 Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: 登入到 Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: 建構並推送 Docker 映像
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: your-docker-hub-username/tony-ecommerce:latest 