name: Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Build Backend
      working-directory: ./backend
      run: |
        ./mvnw clean package -DskipTests
        
    - name: Build Frontend
      working-directory: ./frontend
      run: |
        npm ci
        npm run build
        
    - name: Deploy to Server
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        # 設置 SSH key
        mkdir -p ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        
        # 複製檔案到伺服器
        scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
          backend/target/*.jar \
          $SERVER_USER@$SERVER_IP:/path/to/backend/
        
        scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no -r \
          frontend/build/* \
          $SERVER_USER@$SERVER_IP:/path/to/frontend/
        
        # 重啟服務
        ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
          systemctl restart tony-ecommerce
          systemctl restart nginx
EOF 